### ISSUE TITLE
For multi GPUs: AttributeError: 'DistributedDataParallel' object has no attribute 'set_grid'

### ISSUE THREAD

**Issue by aknirala** [yjh0410/PyTorch_YOLO-Family#26]
I tried training YOLOv2 on coco as:
```
python -m torch.distributed.launch --nproc_per_node=4 train.py -d coco \
                                                               --cuda \
                                                               -m yolov2 \
                                                               -ms \
                                                               --ema \
                                                               -dist \
                                                               --sybn \
                                                               --num_gpu 4 \
                                                               --batch_size 32 \
                                                               --root /data/
```

It started, but than gave error as:
```
use SGD with momentum ...
[Epoch 1/200][Iter 0/924][lr 0.000000][Loss: obj 77.58 || cls 14.72 || reg 4.32 || size 640 || time: 147.40]
[Epoch 1/200][Iter 0/924][lr 0.000000][Loss: obj 82.84 || cls 21.70 || reg 6.05 || size 640 || time: 147.39]
[Epoch 1/200][Iter 0/924][lr 0.000000][Loss: obj 81.38 || cls 22.29 || reg 7.05 || size 640 || time: 147.39]
[Epoch 1/200][Iter 0/924][lr 0.000000][Loss: obj 81.87 || cls 20.74 || reg 6.36 || size 640 || time: 147.38]
Traceback (most recent call last):
  File "/cnvrg/PyTorch_YOLO-Family/train.py", line 515, in <module>
    train()
  File "/cnvrg/PyTorch_YOLO-Family/train.py", line 291, in train
    model.set_grid(train_size)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DistributedDataParallel' object has no attribute 'set_grid'
....

```
Seems like some simple hack could fix it. set_grid which is, in yolov2, is not recognized by model which is now wrapped in DistributedDataParallel

**Comment by aknirala** [comment]
Well, it was fixed easily by:

```
                if args.distributed and args.num_gpu > 1:
                    model.module.set_grid(train_size)
                else:
                    model.set_grid(train_size)
```
